version: '3.1'

services:

  db:
    image: postgres:12-alpine
    volumes:
      - ./data:/var/lib/postgresql
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"